version: "3"
services:
  notebook:
    # Dockerfileからコンテナを構成する
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: qa_practice
    tty: true
    # ブラウザで接続する際のポート設定(順番は"ホストのポート:コンテナのポート")
    ports:
      - 8888:8888
    # 環境変数の設定
    environment:
      - JUPYTER_ENABLE_LAB=yes
    # コンテナ内の/home/jovyan/workディレクトリがホストの./workに反映される
    volumes:
      - ./work:/home/jovyan/work
